import { 
  Utensils, 
  Bus, 
  Home, 
  Gamepad2, 
  Heart, 
  Sparkles, 
  Book, 
  MoreHorizontal,
  Circle,
  TrendingUp,
  TrendingDown,
  Wallet,
  CreditCard,
  Award,
  PiggyBank,
  DollarSign,
  Trophy,
  Medal,
  Shirt,
  Scissors,
  Sparkles as Beauty,
  Briefcase,
  Users,
  Baby,
  Tv,
  Wifi,
  Droplets,
  Plane,
  Bath,
  Palette,
  Footprints,
  Dumbbell,
  UtensilsCrossed,
  Car,
  Music,
  ShoppingBag,
  Zap,
  Camera,
  Phone,
  Coffee,
  Gift
} from 'lucide-react';

interface IconProps {
  name: string;
  className?: string;
  size?: number;
}

const iconMap = {
  'utensils': Utensils,
  'bus': Bus,
  'home': Home,
  'gamepad': Gamepad2,
  'heart': Heart,
  'sparkles': Sparkles,
  'book': Book,
  'more-horizontal': MoreHorizontal,
  'circle': Circle,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  'wallet': Wallet,
  'credit-card': CreditCard,
  'award': Award,
  'piggy-bank': PiggyBank,
  'dollar-sign': DollarSign,
  'trophy': Trophy,
  'medal': Medal,
  'shirt': Shirt,
  'scissors': Scissors,
  'beauty': Beauty,
  'briefcase': Briefcase,
  'users': Users,
  'baby': Baby,
  'tv': Tv,
  'wifi': Wifi,
  'droplets': Droplets,
  'plane': Plane,
  'bath': Bath,
  'palette': Palette,
  'footprints': Footprints,
  'dumbbell': Dumbbell,
  'utensils-crossed': UtensilsCrossed,
  'car': Car,
  'music': Music,
  'shopping-bag': ShoppingBag,
  'zap': Zap,
  'camera': Camera,
  'phone': Phone,
  'coffee': Coffee,
  'gift': Gift,
};

export default function Icon({ name, className = '', size = 20 }: IconProps) {
  const IconComponent = iconMap[name as keyof typeof iconMap] || Circle;
  
  return <IconComponent size={size} className={className} />;
}
